# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fast_brute', [dirname(__file__)])
        except ImportError:
            import _fast_brute
            return _fast_brute
        if fp is not None:
            try:
                _mod = imp.load_module('_fast_brute', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _fast_brute = swig_import_helper()
    del swig_import_helper
else:
    import _fast_brute
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def cdata(*args):
  return _fast_brute.cdata(*args)
cdata = _fast_brute.cdata

def memmove(*args):
  return _fast_brute.memmove(*args)
memmove = _fast_brute.memmove
LENGTH = _fast_brute.LENGTH
INDEX = _fast_brute.INDEX
OUT_LINE_LEN = _fast_brute.OUT_LINE_LEN

def seeds2string(*args):
  return _fast_brute.seeds2string(*args)
seeds2string = _fast_brute.seeds2string

def copy_seeds_list(*args):
  return _fast_brute.copy_seeds_list(*args)
copy_seeds_list = _fast_brute.copy_seeds_list

def num_loc_generated(*args):
  return _fast_brute.num_loc_generated(*args)
num_loc_generated = _fast_brute.num_loc_generated

def is_valid(*args):
  return _fast_brute.is_valid(*args)
is_valid = _fast_brute.is_valid

def find_optimal_seeds(*args):
  return _fast_brute.find_optimal_seeds(*args)
find_optimal_seeds = _fast_brute.find_optimal_seeds
# This file is compatible with both classic and new-style classes.

cvar = _fast_brute.cvar

